import { TabsContext } from '@renderer/context/TabsContext';
import { WorkspaceContext } from '@renderer/context/WorkspaceContext';
import useTheme from '@renderer/hook/useTheme';
import { useEffect, useRef, memo, MutableRefObject, ReactNode, useContext } from 'react';


type Props = {
  exchange: string;
  ticker: string;
};

function TradingViewWidget(props: Props): ReactNode {
  const pExchange: string = props.exchange;
  const pTicker: string = props.ticker;
  const container: MutableRefObject<HTMLDivElement | null> = useRef(null);

  const {activeTheme} = useTheme();
  const {workspaceConfig} = useContext(WorkspaceContext);
  const {activeTabIndex, tabs} = useContext(TabsContext);

  const keyPrefix: string = workspaceConfig.id + "-" + tabs[activeTabIndex].id;

    // THIS IS THE EMBED CODE AS GENERATED BY TRADINGVIEW, MAY NOT BE OPTIMAL!
  useEffect(() => {
    const script = document.createElement("script");
    script.src = "https://s3.tradingview.com/external-embedding/embed-widget-advanced-chart.js";
    script.type = "text/javascript";
    script.async = true;
    script.innerHTML = `
      {
        "autosize": true,
        "symbol": "${pExchange}:${pTicker}",
        "interval": "D",
        "timezone": "Etc/UTC",
        "theme": "${activeTheme}",
        "style": "1",
        "locale": "en",
        "allow_symbol_change": true,
        "calendar": false,
        "support_host": "https://www.tradingview.com"
      }`;
    container.current!.appendChild(script);
  }, [pExchange, pTicker, activeTheme]);

  
  return (
    <div
      className="tradingview-widget-container w-100 h-100" 
      ref={container}
      key={keyPrefix + "-trading-view-real-time-chart-" + pExchange + "_" + pTicker + "_" + activeTheme}
    >
      <div 
        className="tradingview-widget-container__widget" 
        style={{ height: "calc(100% - 32px)", width: "100%" }}
      />
      <div className="tradingview-widget-copyright">
        <a href="https://www.tradingview.com/" rel="noopener nofollow" target="_blank">
          <span className="blue-text">Track all markets on TradingView</span>
        </a>
      </div>
    </div>
  );
}

export default memo(TradingViewWidget);
