import "./AdvancedRealTimeWidget.css";

import useTabKeys from '@renderer/hook/useTabKeys';
import useTheme from '@renderer/hook/useTheme';
import { useEffect, useRef, memo, MutableRefObject, ReactNode, useState } from 'react';
import { ASSETS } from "@renderer/assets/assets";
import StyledIcon from "@renderer/components/StyledIcon/StyledIcon";


type Props = {
  exchange: string;
  ticker: string;
  allowFullscreen?: boolean;
};

export type AdvancedRealTimeWidgetProps = Props;

function AdvancedRealTimeWidget(props: Props): ReactNode {
  const pExchange: string = props.exchange;
  const pTicker: string = props.ticker;
  const pAllowFullscreen: boolean = props.allowFullscreen ?? true;
  const container: MutableRefObject<HTMLDivElement | null> = useRef(null);

  const {activeTheme} = useTheme();
  const {formatKey} = useTabKeys();
  const {theme} = useTheme();

  const [fullscreen, setFullscreen] = useState<boolean>(false);

    // THIS IS THE EMBED CODE AS GENERATED BY TRADINGVIEW, MAY NOT BE OPTIMAL!
  useEffect(() => {
    const script = document.createElement("script");
    script.src = "https://s3.tradingview.com/external-embedding/embed-widget-advanced-chart.js";
    script.type = "text/javascript";
    script.async = true;
    script.innerHTML = `
      {
        "autosize": true,
        "symbol": "${pExchange}:${pTicker}",
        "interval": "D",
        "timezone": "Etc/UTC",
        "theme": "${activeTheme}",
        "style": "1",
        "locale": "en",
        "allow_symbol_change": true,
        "hide_side_toolbar": false,
        "calendar": false,
        "support_host": "https://www.tradingview.com"
      }`;
    container.current!.appendChild(script);
  }, [pExchange, pTicker, activeTheme]);
  
  return (
    <div
      ref={container}
      key={formatKey(
        "trading-view-real-time-chart-" + pExchange + "_" + pTicker + "_" + activeTheme
      )}
      style={fullscreen ? {
        position:"fixed",
        top: "0px",
        left: "0px",
        width: "100%",
        height: "100%",
        zIndex: 2
      } : {}}
      {...theme("ambient-bgc", "tradingview-widget-container w-100 h-100")}
    >
      <div 
        className="tradingview-widget-container__widget" 
        style={{ height: "calc(100% - 32px)", width: "100%" }}
      />
      <div className="advanced-real-time-widget-bottom">
        <div className="tradingview-widget-copyright">
          <a
            href="https://www.tradingview.com/"
            rel="noopener nofollow" 
            target="_blank"
          >
            <span className="blue-text">Track all markets on TradingView</span>
          </a>
        </div>
        {pAllowFullscreen && (<StyledIcon
          iconSize="advanced-real-time-widget-fullscreen"
          src={ASSETS.icons.action.fullscreen.black}
          onClick={() => pAllowFullscreen && setFullscreen(!fullscreen)}
        />)}
      </div>
    </div>
  );
}

export default memo(AdvancedRealTimeWidget);
